version: '3.7'

services:

  metricbeat:
    hostname: metricbeat
    image: docker.elastic.co/beats/metricbeat:7.3.1
    user: root
    volumes:
      - ./config/metricbeat/init.sh:/init.sh
      - ./config/metricbeat/metricbeat.yml:/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    links:
      - elasticsearch

  filebeat:
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:7.3.1
    user: root
    command: 'bash /init.sh'
    volumes:
      - ./config/filebeat/init.sh:/init.sh
      - ./config/filebeat/filebeat.yml:/filebeat.yml
      - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - logstash

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    hostname: kibana
    environment:
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - 127.0.0.1:5601:5601
      
  logstash: 
    image: docker.elastic.co/logstash/logstash:7.3.1
    hostname: logstash
    volumes:
      - ./config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    environment:
      LOG_LEVEL: error
    links:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    hostname: elasticsearch
    #volumes:
    #  - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data      
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 127.0.0.1:9200:9200

volumes:
  elasticsearch: